services:
  - type: web
    name: ultraviolet-proxy
    env: node
    region: Singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    branch: main
    autoDeploy: true
